### ISSUE TITLE
Are you moving back from Texas?

### ISSUE THREAD

**Issue by carlmjohnson** [SimmonsRitchie/aopc-simple-scraper#1]

**Comment by SimmonsRitchie** [comment]
Hah, not quite! A reporter in Pa. recently asked me if [this scraper](https://github.com/SimmonsRitchie/court_docket_scraper) I wrote a few years ago still works (it doesn't). I had some code that handles the newer version of AOPC's website so I figured I'd upload it to help him out. I'm hoping it might be useful to other Pa. reporters out there too 🙌
